### ISSUE TITLE
The bot doesn't reply (The Card-Bot code)

### ISSUE THREAD

**Issue by AnassSaikouk** [gsuitedevs/hangouts-chat-samples#12]
Hey, 
I tried to test the java  code source in order to create a card bot.
I found two problems: 
1) the method asJsonObject() is undefined in the case : "CARD_CLICKED", so i can't run the project.
2) i tried to comment the case "CARD-CLICKED" and  test just the case: "Message" but it doesn't work, i receive on my  bot "the bot can't reply" .
Can you please tell me if the error is from the source code? does someone test the card bot with java source code ? 
Thanks :)

**Comment by erickoledadevrel** [comment]
Can you point to the exact sample and line that is causing an issue? The basic bot doesn't use cards, and I just tested the card bot sample and it worked without any issues.

**Comment by AnassSaikouk** [comment]
Yes, sorry i meant the Card-bot code.
1 - the problem is in the Servlet BotServlet: 

the error is : "the method asJsonObject() is undifined for the type JsonValue"  

![capture d ecran 14](https://user-images.githubusercontent.com/27215248/40710555-3c57cc12-63f9-11e8-9c75-72238cbbf389.png)

Can you please tell me which version of Java you use ? may be this is the reason why i get this error ?
2- I tried to comment the case "CARD_CLICKED" beacause it contains the asJsonObject() method 
and run the project but the answer i got on my chat bot is the bot doesn't reply "in French : ne réponds pas" : 
![capture d ecran 15](https://user-images.githubusercontent.com/27215248/40710960-4b04f446-63fa-11e8-8b88-72b3b0872625.png) 

waiting for your answer, Thanks!

**Comment by Dan243** [comment]
I had the same issues @erickoledadevrel. How did you just import and test your code ?

**Comment by erickoledadevrel** [comment]
I deployed the code to App Engine, and that line runs without error. Are you deploying to App Engine or some other environment. I suspect it has something to do with different JSON parsers.

**Comment by AnassSaikouk** [comment]
Hey @erickoledadevrel,
Yes i deployed to App Engine.
I tried to Parse the  asJsonObject() but it doesn't work.

**Comment by AnassSaikouk** [comment]
Update : the card-bot work, i've just change the version of AppEngine SDK ( from appengine-java-sdk-1.9.63 to appengine-java-sdk-1.9.64 ) 

Thanks @erickoledadevrel for your answers.
