### ISSUE TITLE
Google APIs returns only list of space Id of users who have added Google Chat Bot to their coversation

### ISSUE THREAD

**Issue by savi-ganesh** [gsuitedevs/hangouts-chat-samples#14]
We are implementing a Google hangout Chat Bot , Which will send proactive notification to the user in domain. To do this Google chat Bot API requires the space Id to send proactive notification to user.

Reference document: https://developers.google.com/hangouts/chat/reference/rest/v1/spaces/list

But This API returns space list of only those user , who has added the Bot to their coversation.

Is their any work around to get/create space of/to every user in google domain?

**Comment by erickoledadevrel** [comment]
This issue tracker is for problems with the samples in this repo. For general support options see this page:

https://developers.google.com/hangouts/chat/support

The Hangouts Chat API currently doesn't support pro-active messaging of a user. A bot can only communicate with a user after the user has started a DM with the bot or @mentioned the bot in a room.

**Comment by zeeshanbage** [comment]
its been 2 years now so asking again, is there any work around to get space id of every user? or hangout api still doesn't support it?
