### ISSUE TITLE
Python Card-bot not responding 

### ISSUE THREAD

**Issue by Zhipeng-Chang** [gsuitedevs/hangouts-chat-samples#17]
Hi, 
I'm having a problem to run the card-bot, it shows 500 internal error. 
After I deployed it, it shows:
"JacksonBot not responding
Only visible to you" (JacksonBot is my bot name)
I attached some screenshots at the bottom 
![image](https://user-images.githubusercontent.com/22534832/45259646-a59c1e00-b38e-11e8-9862-601ca50ccb51.png)
![image](https://user-images.githubusercontent.com/22534832/45259648-a9c83b80-b38e-11e8-987d-708b78d2e341.png)

**Comment by TusharTelus** [comment]
Hi 
How did you resolve this issue.

**Comment by diaowenyang** [comment]
@jackson-zhipeng-chang How did you resolve this issue?
