### ISSUE TITLE
Error out when click interactive card button

### ISSUE THREAD

**Issue by clement9527** [gsuitedevs/hangouts-chat-samples#19]
Hi there,

I wrote up a simple bot which does nothing but an interactive button. I tested using the console, and I am able to see the message in the chat room. However, when I click the button, it spin for a while and then show the error message 'Unable to contact. Try again later.'  

I am expecting the CARD_CLICKED event to be trapped by the console log statement. However, there is no such entry in the log. Is there anything I missed in the configuration?

```
const axios = require('axios');
const url = [CHAT_ROOM_WEBHOOK];

function createCard() {
    return {
        'cards': [{
            'sections': [{
                'widgets': [{
                    'buttons': [{
                        'textButton': {
                            'text': 'Grab it',
                            'onClick': {
                                'action': {
                                    'actionMethodName': 'snooze'
                                }
                            }
                        }
                    }]
                }]
            }]
        }]
    };
}

/**
 * Responds to any HTTP request.
 *
 * @param {!express:Request} req HTTP request context.
 * @param {!express:Response} res HTTP response context.
 */
exports.main = (req, res) => {
    console.log(JSON.stringify(req.body));
    const card = createCard(req.body);
    axios
        .post(url, card)
        .then(response => {
            res.status(200).send(card);
        })
        .catch(error => {
            res.status(500).send(error);
        });
};
```

Please help.

**Comment by erickoledadevrel** [comment]
This issue tracker is for reporting bugs in our sample code. For general developer support please see the options listed here:

https://developers.google.com/hangouts/chat/support

**Comment by clement9527** [comment]
Thanks for your comment, I have post my question on [StackOverflow](https://stackoverflow.com/questions/52428451/error-out-when-click-google-chat-bot-interactive-button).  Please kindly give me some help on it.

**Comment by clement9527** [comment]
I have the question sitting there for a while, do you mind taking some time just give me a hand on that. Much appreciated.

**Comment by nvtuan305** [comment]
I got the same issue. @clement9527 Do you have any solutions?
