### ISSUE TITLE
Cards are not rendered until I refresh hangouts page

### ISSUE THREAD

**Issue by meghabh** [gsuitedevs/hangouts-chat-samples#68]
Hi ,

I have created a bot  using Bot url (API Gateway API)which sends message/cards to bot . It used to work properly. Suddenly Response cards are not rendering and once I refresh the page it shows up.

Did anyone face this issue? Or any thoughts on this.

Thank you in advance

**Comment by meghabh** [comment]
we tested this with simple card withouts buttons. It renders properly. But Not with complex cards with buttons

**Comment by sqrrrl** [comment]
THanks for reaching out, but this issue tracker is only for issues with the samples themselves. See https://developers.google.com/hangouts/chat/support for other support options. Specifically, if you think there's a bug with Hangouts Chat itself you can file an issue on the tracker listed on that page. If you're a G Suite customer, you can also contact support for assistance.
