### ISSUE TITLE
Non-G Suite version?

### ISSUE THREAD

**Issue by cyraid** [gsuitedevs/hangouts-chat-samples#8]
It appears the examples do not work with a non-g suite service account. Some (sadly like myself) wasted a bit of time just to find out you can't use it with non-g suite. Some more warnings would be nice in the readme (or maybe we can recommend or vote for personal account support?)

It mentions that it integrates with g-suite but not exclusively and does not clearly state it *only* works with g-suite.. unless I glazed it over in my less than fully awake state ;)

**Comment by erickoledadevrel** [comment]
Can you clarify what didn't work? As far as I know, there isn't such a thing as a "G Suite service account". It is true that Hangouts Chat itself is only available in G Suite, but I'm not aware of any restrictions as to what types of service accounts can power the bot.

**Comment by cyraid** [comment]
Sorry by non G Suite account I meant personal account. Have you not tried using a personal account? It gave me a permissions error when I tried to go to the configuration on the Google Console. Know of any way around this?

**Comment by BaReinhard** [comment]
I believe hangouts chat is strictly for enterprise, and hangouts classic is for personal.

**Comment by cyraid** [comment]
Would you know of an API for hangouts classic (for personal)?

**Comment by BaReinhard** [comment]
I don’t think it’s active anymore but it should still be listed in the api and services inside gcp

**Comment by erickoledadevrel** [comment]
I added a note to the README.
